sudo: required
dist: trusty
language: node_js
node_js:
- '6'
before_install:
- npm i -g npm@5
cache:
  directories:
  - node_modules
env:
  global:
  - RUN_MODE=dev
  - MX_APP_NAME=widgetbuildscript
  - MX_PROJECT_ID=3df7b609-e8f6-4d28-8e3c-6e665d914c19
  - MX_USER=ci@flockofbirds.org
  - secure: CeWkYkGCDI3mHFZEe/3lD7FHBQqvCmCZuwxNeVsL2Q7Ho92/VIbuGtPNUGXzSY+UdswSwKYCE3AcCe5Q2l1XEgJ9SgN/MbU1/bdFmiPmstt68AH7NvNGDAEZFD6WX2WihoZGNYkTnO4dlixplmX3PYD9OJh6dwRb99bvUT4Eu8dVqYfooPdD3ltO3oH/1gsKBd7ymmK2XHZVBBOWuc7/UPv84ueITmVt+ba7A0vv/zPDPXpKNPoUL00f4yQVfjdq9T238J1WVWLrbSv7K2XQK6fJn0/63qXOgoEKC7jZ17NbC6L6BaGzf7eKhSz9d+4AY8HGDbaqG45hAB/RTEdQcbpMwlzJwVYtKPCXZSYGpW0f4jdpfxvkEnVOhJNMyO+sCwyaoIiuhBlDXTd1axrlaXxgwMIwq0Oka+qE90M/tCGgueSVC0Q00r0oOAbcslDf6fHLFoKtU0ILavJ30J5CEfQIJaEYFxpNxVS0WGNJEa1BQdPwcOT+8bMONjVX7HQ3BJb/gj0ekiST1vftqQKs2OV3jJsVebYdPsMXRM4bzgB3nAvlmHb/ahSJBthVVAxdnnWD44r6jocRujBelfbT1C7TdLmdJ/PkDRy+98HclDh9dCMSt7J7SJKyGHHk2kZPD0WajCOWS39by6MAaz6Qfu0+B5/OEZedmiELBUT4BeE=
  - secure: mapjkHJ+JbThW9xLK8h3yM7ZhmrrT950hnlxtZb1Hrb+Yw6AA+XLJMwpmdxhEPtcaEaehb+sE28QzCPPfkTx0JANHso2aBYrqFHjpBMYMBCSO+38Q0DPjuAtuA1fa9oDiR8Sv2+kORVB8cwDxMYMvvQtiI1dGLautk+e2WhDwb4Qo+uFQTuQj2Lk2gcA4A0yAZHcWx05BnN0El8kSGrAjE0b5FjNOjXZ8JACkEEE0rHZBrMsCkCZZ42fv/wP6PpHbNCwTY0+WK/hdgXnzvEF2LkvX+q96D9oMS88Kf+fjTcJCDHnKdhPRmTq/8cNwfTaOsmJovmtbY4LJUQHNsBuXpaer1YxZC0ouAQv4bBbADO0BrBv/ZpGjI5rNo/l7NyfaM2+CmAU+DrHRz0MGZWnSCJ7Yh8xvVmr22Yimgso2dnTJx2ajIOxAkbL5yXL6vbixWccW6Ic2PzKCuChllsv7poxNNtd7s5FbaTs1brGG9Qzs7iK8htPjzK11Z4DTcbFabovPcZ15fcUoaTeIe2+reCmEzReA+C9s230AGyVlYHtn9GhMm8TAb6DD6ush40J462EhFY/Waz9poy1dgtx+dhMfE3cSHfI5wsyoYKZdw25IK+qdidBcRqBvkCnznFCS1OoLG0FqO4FnvgXwvXF37Jps+i3r8V4Hu4y4hryj8s=
deploy:
  provider: npm
  email: ci@flockofbirds.org
  api_key:
    secure: Agql4s6Bx3vG82NpUnLR2Rj4metr/peA/y3Wj/cwMZMfszb3Sz0Uaa4a4egNegbt4DsDaC9Abq/RwUfEFd27BYRb3bxE4UwRgHGFpUkQPXmi0eh/Q2jxrtKZLIYd+4kQTg0b1+3EXZJg3JO1zlGOJuzOL4K+3W/2rEP0Wn1DPYz7CES+oIEnGBK4yJb6AooOJF09qqme/2rEhdEvNoyYN2/yB2aS79FRrOMGDffxT5t/BHjCiwylf4SBsNsGVsJhef5PZDS6PBN5yJ7C3fkl0jGyhyrLO7DEGq6XoSQ7IydBnr+rgiZ9H4nnFDamvZTBO6xguQ1cg8w5+zCxXowVD9my0rxV9FdfoG/X+xXFdH46jaxocRF3vfBD3s8k4Ni6WkrzLypdyhR5qH+FrV7QWhwjmPTHHZwUt6QxbQTGhQ9Vv0YElSpipjwBhZQhV3IyIcvbVfuVXdT74toZOctMbUzo4/xst4j199pBnxxAFdn4m+tmfxXdpI/eB1R9DbPjRwrxnx7vEhhRwiE44VRazOjaLkZpUWi/M7SkGU6GssmTpBekchbf/13OCvo1H8QbpXjtCdaVshZMGkgaSN0sRx37BU9gDDgJ4ia+RMJrDSADmHd9RtDiQzRfZZD7eRSyhsuNfLe+4lTc13+0RuadqsmbqW/u+jZ48kZYA43T3Fw=
  on:
    tags: true
    repo: FlockOfBirds/mendix-widget-build-script
