sudo: required
language: node_js
node_js:
- '6'
before_install:
- npm i -g npm@latest
cache:
  directories:
  - node_modules
env:
  global:
  - RUN_MODE=dev
  - MX_APP_NAME=widgetbuildscript
  - MX_PROJECT_ID=3df7b609-e8f6-4d28-8e3c-6e665d914c19
  - MX_USER=ci@flockofbirds.org
  - secure: CeWkYkGCDI3mHFZEe/3lD7FHBQqvCmCZuwxNeVsL2Q7Ho92/VIbuGtPNUGXzSY+UdswSwKYCE3AcCe5Q2l1XEgJ9SgN/MbU1/bdFmiPmstt68AH7NvNGDAEZFD6WX2WihoZGNYkTnO4dlixplmX3PYD9OJh6dwRb99bvUT4Eu8dVqYfooPdD3ltO3oH/1gsKBd7ymmK2XHZVBBOWuc7/UPv84ueITmVt+ba7A0vv/zPDPXpKNPoUL00f4yQVfjdq9T238J1WVWLrbSv7K2XQK6fJn0/63qXOgoEKC7jZ17NbC6L6BaGzf7eKhSz9d+4AY8HGDbaqG45hAB/RTEdQcbpMwlzJwVYtKPCXZSYGpW0f4jdpfxvkEnVOhJNMyO+sCwyaoIiuhBlDXTd1axrlaXxgwMIwq0Oka+qE90M/tCGgueSVC0Q00r0oOAbcslDf6fHLFoKtU0ILavJ30J5CEfQIJaEYFxpNxVS0WGNJEa1BQdPwcOT+8bMONjVX7HQ3BJb/gj0ekiST1vftqQKs2OV3jJsVebYdPsMXRM4bzgB3nAvlmHb/ahSJBthVVAxdnnWD44r6jocRujBelfbT1C7TdLmdJ/PkDRy+98HclDh9dCMSt7J7SJKyGHHk2kZPD0WajCOWS39by6MAaz6Qfu0+B5/OEZedmiELBUT4BeE=
  - secure: ZyN7TDCdRltQYm73DGNAPtBbpbD43Jhd4LUWkzmABjCIF9c7KLru+ZmDRNnaxgymp3IZTu8j+9MscUyRR3by6hExo1lJVIkm4hhEQv+zstHXXpUS9jVsB/cLrbyRZ6tgK9O1avbttwtRiDpm+HRjWhQ8L6GKFjrKEyTuvGmvfaJoAI4meqjFdVXC8wHPUZ+vuWpqnC0GBzLZe8K5I0souoBr2MyGcpGjm26+kQE48MHEgfMQHLeQvjuT4BUIcBGhezfBTcFdyxh0ZWPVrriwTUYGskfQIGcztD/k1bryD4UFUX0OMXvGHEZqC4/IeAT6mFzYEkasQzmeGDWOEuVVu+zDAyP5Y8b1deZUVi11fgyS/XjQA3PZZwJRbV82T2yvO9ioyAmuBSX0lBqX9ub50LuHCYTbLAH3wRJRMSLsk6M2vrP2VigrdUmlyEvy4Qe4863VhYyXAS+S6zD3OXX+zY2k3ZtWFXwzHIszjsmUjjNTEapcSq20ezCz7s16DI3VlpYtU+dA45w6em5N2F2fvcPrXyN2XVe8QT5TJYgLPuD9uCOjJPM1DuaGIZBQuHragIlLGXq4qowfdd3vyNvXhZ1fNlFQLaWDf+0TOQEgenDQqTNskmGAA5HA5xwc4DVrF02JNg/jHOtB5kCcz5/FfPjiBgjot6q1wEdJeJ97Wn4=
deploy:
  provider: npm
  email: ci@flockofbirds.org
  skip_cleanup: true
  api_key:
    secure: Agql4s6Bx3vG82NpUnLR2Rj4metr/peA/y3Wj/cwMZMfszb3Sz0Uaa4a4egNegbt4DsDaC9Abq/RwUfEFd27BYRb3bxE4UwRgHGFpUkQPXmi0eh/Q2jxrtKZLIYd+4kQTg0b1+3EXZJg3JO1zlGOJuzOL4K+3W/2rEP0Wn1DPYz7CES+oIEnGBK4yJb6AooOJF09qqme/2rEhdEvNoyYN2/yB2aS79FRrOMGDffxT5t/BHjCiwylf4SBsNsGVsJhef5PZDS6PBN5yJ7C3fkl0jGyhyrLO7DEGq6XoSQ7IydBnr+rgiZ9H4nnFDamvZTBO6xguQ1cg8w5+zCxXowVD9my0rxV9FdfoG/X+xXFdH46jaxocRF3vfBD3s8k4Ni6WkrzLypdyhR5qH+FrV7QWhwjmPTHHZwUt6QxbQTGhQ9Vv0YElSpipjwBhZQhV3IyIcvbVfuVXdT74toZOctMbUzo4/xst4j199pBnxxAFdn4m+tmfxXdpI/eB1R9DbPjRwrxnx7vEhhRwiE44VRazOjaLkZpUWi/M7SkGU6GssmTpBekchbf/13OCvo1H8QbpXjtCdaVshZMGkgaSN0sRx37BU9gDDgJ4ia+RMJrDSADmHd9RtDiQzRfZZD7eRSyhsuNfLe+4lTc13+0RuadqsmbqW/u+jZ48kZYA43T3Fw=
  on:
    tags: true
    repo: FlockOfBirds/mendix-widget-build-script
