sudo: required
dist: trusty
language: node_js
node_js:
- '6'
before_install:
- npm i -g npm@5
- npm install grunt-cli -g
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget -q -O - http://opensource.wandisco.com/wandisco-debian.gpg | sudo apt-key add -
- sudo sh -c 'echo "deb http://opensource.wandisco.com/debian/ wheezy svn17" > /etc/apt/sources.list.d/wandisco-subversion.list'
- sudo apt-get -qq update
- sudo apt-get install -y --allow-downgrades subversion=1.7.22-1+WANdisco libsvn1=1.7.22-1+WANdisco
- svn --version
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - node_modules
env:
  global:
  - MX_API_URL=https://deploy.mendix.com/api/1
  - MX_APP_NAME=appName
  - MX_TEAM_SERVER_URL=https://teamserver.sprintr.com
  - MX_BRANCH_NAME=trunk
  - secure: Z/onZeXXLhah228r/Iijn4g+MiPairgdY/wq0mgUXfYHcI=
  - MX_ENVIRONMENT=Sandbox
  - MX_PROJECT_ID=xxxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxxxx
  - MX_USER=ci@example.org
  - secure: iexj9Th1Tq07AWIK7MyvrlFCVI7JhfQ3D5zLJSuo78ZN=
deploy:
  provider: releases
  api_key:
    secure: mQtgwYHfLN8JGuTUQfKrBxJsGw5oG9ii0qa8gBDQL5=
  file_glob: true
  file: dist/release/*
  skip_cleanup: true
  on:
    repo: github-user/github-repo
    tags: true
